# Generated by Django 3.2.8 on 2021-11-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_webside_profile_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bigoraphy',
            new_name='biography',
        ),
    ]
