# Generated by Django 3.2.8 on 2021-11-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_biography_profile_bigoraphy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bigoraphy',
            new_name='biography',
        ),
    ]
